version: "3.8"

services:
   mariadb:
      image: mariadb
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: root@123
         MYSQL_DATABASE: aurondb
      ports:
         - "3306:3306"